import pandas as pd
import numpy as np
from ta.trend import MACD, SMAIndicator, EMAIndicator
from ta.momentum import RSIIndicator, StochasticOscillator
from ta.volatility import BollingerBands, AverageTrueRange
from ta.volume import OnBalanceVolumeIndicator

def add_technical_indicators(df: pd.DataFrame) -> pd.DataFrame:
    """
    Add technical indicators to the DataFrame.
    """
    if df.empty:
        return df
    
    # Ensure data is sorted
    df = df.sort_values('open_time').reset_index(drop=True)
    
    # --- Trend Indicators ---
    # MACD
    macd = MACD(close=df['close'])
    df['macd'] = macd.macd()
    df['macd_signal'] = macd.macd_signal()
    df['macd_diff'] = macd.macd_diff()
    
    # SMA / EMA
    df['sma_20'] = SMAIndicator(close=df['close'], window=20).sma_indicator()
    df['ema_50'] = EMAIndicator(close=df['close'], window=50).ema_indicator()
    df['ema_200'] = EMAIndicator(close=df['close'], window=200).ema_indicator()
    
    # --- Momentum Indicators ---
    # RSI
    df['rsi'] = RSIIndicator(close=df['close'], window=14).rsi()
    
    # Stochastic
    stoch = StochasticOscillator(high=df['high'], low=df['low'], close=df['close'])
    df['stoch_k'] = stoch.stoch()
    df['stoch_d'] = stoch.stoch_signal()
    
    # --- Volatility Indicators ---
    # Bollinger Bands
    bb = BollingerBands(close=df['close'], window=20, window_dev=2)
    df['bb_high'] = bb.bollinger_hband()
    df['bb_low'] = bb.bollinger_lband()
    df['bb_mid'] = bb.bollinger_mavg()
    df['bb_width'] = (df['bb_high'] - df['bb_low']) / df['bb_mid']
    
    # ATR
    df['atr'] = AverageTrueRange(high=df['high'], low=df['low'], close=df['close'], window=14).average_true_range()
    
    # --- Volume Indicators ---
    # OBV
    df['obv'] = OnBalanceVolumeIndicator(close=df['close'], volume=df['volume']).on_balance_volume()
    
    # Drop NaN values generated by indicators
    df = df.dropna().reset_index(drop=True)
    
    return df

def add_target_model_a(df: pd.DataFrame, horizon: int = 1) -> pd.DataFrame:
    """
    Create target labels for Model A (Trend/Direction).
    Target: 1 if next close > current close, 0 otherwise.
    Future Return: (Close_{t+n} - Close_t) / Close_t
    """
    df['future_close'] = df['close'].shift(-horizon)
    df['target_return'] = (df['future_close'] - df['close']) / df['close']
    df['target_direction'] = (df['future_close'] > df['close']).astype(int)
    
    # Drop last 'horizon' rows as they have no target
    df = df.dropna(subset=['future_close']).reset_index(drop=True)
    return df
